stages:
  - deploy
  - test

deploy:
  stage: deploy
  image: python:3.11
  script:
    - pip install -r ./microblog/requirements.txt
    - ./microblog/boot.sh
    - sleep 5

crawler-test:
  stage: test
  image: python:3.11
  services: 
    - selenium/standalone-chrome
  script:
    - pip install selenium
    - pip install pyvirtualdisplay
    - python -m ./crawler/crawler.py
